(function(){
const D=window.TR_DATA||{};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=s=>(s??'').toString().replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
const attr=s=>esc(s).replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const icon=(k,n='')=>{const t=(k+' '+n).toLowerCase();if(/galin|coop|chicken/.test(t))return'🐔';if(/barn|celeiro|cow|sheep|pig|vaca|ovelha|porco/.test(t))return'🐄';if(/pick|axe|machado|picareta|tool|ferro|ferr/.test(t))return'⚒️';if(/fish|peixe|pesc|kujaku|sardinha|anchovy|trout|salmon/.test(t))return'🐟';if(/bee|honey|mel|apiary|abelha/.test(t))return'🐝';if(/jacky|cat|gato|nessy/.test(t))return'🐈';if(/seed|sprout|semente|farm|crop/.test(t))return'🌱';if(/recipe|receita|food|comida|prato/.test(t))return'🍲';if(/brew|beer|cerveja|wine|ale|mead|hidromel/.test(t))return'🍺';if(/wood|madeira|carp|sawmill/.test(t))return'🪵';if(/mine|ore|cobalt|iron|mina/.test(t))return'⛏️';if(/rilia|map|local/.test(t))return'🗺️';if(/crafter|station|table|bench|forage|smelter/.test(t))return'🧰';return'📜'};
const panel=(t,b,l='')=>`<div class='panel'><div class='section-title'><h2>${t}</h2>${l}</div>${b}</div>`;
const norm=s=>(s||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function rawText(o){return Object.entries(o||{}).map(([k,v])=>Array.isArray(v)?k+': '+v.join(', '):k+': '+v).join(' • ')}
function legacy(){const out=[];function add(kind,arr,key='name',fields=[]){(arr||[]).forEach(e=>{const name=e[key]||'';const desc=fields.map(f=>e[f]).filter(Boolean).join(' • ')||rawText(e);out.push({kind,name,desc,...e})})}add('Ferramenta',D.tools,'name',['tier','recipe','use']);add('NPC / Loja',D.vendors,'name',['shop','hours','sells']);add('Local',D.locations,'name',['type','notes']);add('Material',D.materials,'name',['group','get','notes','materials','upgrades']);add('Pesca',D.fish,'name',['type','get','notes']);add('Receita',D.food,'name',['category','ingredients','notes']);add('Brewing',D.brewing,'name',['station','ingredients','notes']);add('Semente',D.seeds,'name',['category','season','source']);add('Quest',D.quests,'name',['notes']);return out}
const R=(D.catalog&&D.catalog.length?D.catalog:legacy()).map(x=>{x.kind=x.kind||x.category||'Item';x.name=x.name||x.title||'Sem nome';x.desc=x.desc||x.summary||x.notes||rawText(x);x.search=[x.name,x.kind,x.desc,x.aliases,rawText(x)].flat().join(' ');return x});
const todos=['Liberar a mina / Ferro','Fazer Iron Pickax','Fazer Iron Axe','Construir Galinheiro','Comprar Galinha','Pegar Queen Bee','Fazer Apiary','Achar Jacky','Farmar Cobalt'];
function taskList(prefix){return todos.map((t,i)=>`<label class='task' data-persist='${prefix}-${i}'><input type='checkbox'><span class='task-icon'>${icon('task',t)}</span><span class='task-text'>${esc(t)}</span><span class='task-count'>0/1</span></label>`).join('')}
function card(r,cls='item-card'){const raw=attr(encodeURIComponent(JSON.stringify(r)));return `<article class='${cls} db-source detail-source' data-title='${attr(r.name)}' data-kind='${attr(r.kind)}' data-desc='${attr(r.desc||'')}' data-raw='${raw}' data-text='${attr(norm(r.search))}'><button class='fav' type='button'>★</button><div class='item-art'>${icon(r.kind,r.name)}</div><h3>${esc(r.name)}</h3><span class='tag'>${esc(r.kind)}</span><p>${esc((r.desc||'').slice(0,150))}</p><button class='more-info' type='button'>Mais infos</button></article>`}
function renderHome(){const want=['Iron Pickax','Oily Fish','Jacky','Queen Bee','Chicken Coop / Galinheiro'];const feat=want.map(n=>R.find(r=>norm(r.name).includes(norm(n.split('/')[0].trim()))||norm(r.search).includes(norm(n)))||{name:n,kind:'Destaque',desc:'',search:n});const shortcuts=`<div class='shortcut-grid'><a class='shortcut' href='#database'><span>📦</span>Itens</a><a class='shortcut' href='#database'><span>🍲</span>Receitas</a><a class='shortcut' href='#rilia'><span>🏘️</span>Rilia</a><a class='shortcut' href='#planner'><span>🧮</span>Planner</a></div>`;$('#home').innerHTML=panel('Destaques',`<div class='h-scroll'>${feat.map(card).join('')}</div>`,'<a href=#database>Ver todos ›</a>')+panel('Checklist rápido',taskList('home'),'<a href=#guia>Meu guia ›</a>')+panel('Atalhos rápidos',shortcuts)}
function renderGuia(){const orders=[['🍲','Sopa de Abóbora','Yoren','75','1 dia'],['🍺','Cerveja Clara','Mira','60','2 dias'],['🐟','Peixe Grelhado','Jacky','80','2 dias']].map(o=>`<div class='order-row'><span>${o[0]}</span><div><b>${o[1]}</b><small>para ${o[2]}</small></div><span class='coin'>🪙 ${o[3]}</span><span class='deadline'>⏱ ${o[4]}</span></div>`).join('');const inv=[['🪵','Madeira',126],['🪨','Pedra',84],['🌾','Trigo',63],['🪙','Moedas',41],['🐟','Peixe',22],['🍺','Barril',18],['🥩','Carne',15],['🍯','Mel',10]].map(x=>`<div class='inv-slot'><span>${x[0]}</span><b>${x[2]}</b><small>${x[1]}</small></div>`).join('');const stats=`<div class='tavern-stats'><div class='stat-line'><span>🏠 Nível da Taverna</span><b>8</b><div class='bar'><i></i></div></div><div class='stat-line'><span>❤️ Reputação</span><b>1.240</b></div><div class='stat-line'><span>🧑 Clientes atendidos</span><b>152</b></div><div class='stat-line'><span>🪙 Receita do mês</span><b>1.856</b></div></div>`;$('#guia').innerHTML=panel('Meu guia',taskList('guia'),'<button id=resetTodos>Resetar</button>')+`<div class='two-col'>${panel('Pedidos ativos',orders)}${panel('Inventário rápido',`<div class='inv-grid'>${inv}</div>`)}</div>`+panel('Sua taverna',stats);$('#resetTodos').onclick=()=>{localStorage.removeItem('trg-todos');$$('.task input').forEach(i=>i.checked=false)}}
function renderDatabase(){const cats=['all',...Array.from(new Set(R.map(r=>r.kind))).sort()];$('#categorySelect').innerHTML=cats.map(c=>`<option value='${attr(c)}'>${c==='all'?'Todos':esc(c)}</option>`).join('');const chips=cats.slice(0,12).map((c,i)=>`<a class='chip ${i?'':'active'}' href='#database' data-filter='${attr(c)}'>${c==='all'?'Todos':esc(c)}</a>`).join('');$('#database').innerHTML=panel('Base de dados',`<div class='chips'>${chips}</div><div class='db-meta'><span id='resultCount'>${R.length} itens</span></div><div class='db-list' id='dbList'>${R.map(r=>card(r,'db-card')).join('')}</div><div id='emptyState' class='empty-state'>Nada encontrado.</div>`)}
function renderRilia(){const vendors=(D.vendors||[]).map(v=>card({kind:'NPC / Loja',name:v.name,desc:[v.shop,v.hours,v.sells].filter(Boolean).join(' • '),...v},'vendor-card')).join('');const locs=(D.locations||[]).map(l=>card({kind:'Local',name:l.name,desc:[l.type,l.notes].filter(Boolean).join(' • '),...l},'mini-card')).join('');$('#rilia').innerHTML=panel('Rilia — vendedores',vendors)+panel('Locais',`<div class='mini-grid'>${locs}</div>`)}
function renderPlanner(){const tools=(D.tools||[]).filter(t=>/Iron|Cobalt|Ferro|Cobalto/.test(t.name));const recipes=tools.map((t,i)=>`<label class='planner-recipe'><input type='checkbox' data-recipe='${i}' data-recipe-text='${attr(t.recipe)}'><span class='tool-icon'>${icon('tool',t.name)}</span><span><b>${esc(t.name)}</b><small>${esc(t.recipe)}</small></span></label>`).join('');const inv=`<div class='inventory-inputs'><label>Iron Bar<input type='number' min=0 value=0 data-inv='Iron Bar'></label><label>Cobalt Bar<input type='number' min=0 value=0 data-inv='Cobalt Bar'></label><label>Wooden Planks<input type='number' min=0 value=0 data-inv='Wooden Planks'></label><label>Noble Planks<input type='number' min=0 value=0 data-inv='Noble Wooden Planks'></label></div>`;$('#planner').innerHTML=panel('Planner de upgrades',inv)+panel('Escolha os upgrades',recipes)+panel('Faltando',`<div id='missingBox'><p style='position:relative;z-index:1;color:var(--muted)'>Marque um upgrade para calcular.</p></div>`)}
function renderFontes(){const list=(D.sources||[]).map(s=>`<li><a href='${esc(s.url)}' target='_blank'>${esc(s.label)}</a><span>${esc(s.why)}</span></li>`).join('');$('#fontes').innerHTML=panel('Fontes',`<p style='position:relative;z-index:1;color:var(--muted)'>Guia fan-made. Em update grande, confira valores específicos.</p><ul class='sources-list'>${list}</ul>`)}
function filter(){const q=norm($('#searchInput').value),cat=$('#categorySelect').value||'all';let n=0;$$('#dbList .db-source').forEach(c=>{const ok=(!q||norm(c.dataset.text).includes(q))&&(cat==='all'||c.dataset.kind===cat);c.hidden=!ok;if(ok)n++});if($('#resultCount'))$('#resultCount').textContent=n+(n===1?' item':' itens');if($('#emptyState'))$('#emptyState').classList.toggle('show',n===0)}
function calc(){const inv={};$$('[data-inv]').forEach(i=>inv[i.dataset.inv]=Number(i.value||0));const total={};$$('[data-recipe]:checked').forEach(i=>{let m,rx=/(\d+)\s+([A-Za-z ]+?)(?=\s\+|$)/g;while((m=rx.exec(i.dataset.recipeText||''))){let k=m[2].trim();if(k==='Iron Bars')k='Iron Bar';if(k.includes('Cobalt'))k='Cobalt Bar';if(k==='Wooden Plank')k='Wooden Planks';if(['Iron Bar','Cobalt Bar','Wooden Planks','Noble Wooden Planks'].includes(k))total[k]=(total[k]||0)+Number(m[1])}});const box=$('#missingBox');if(!Object.keys(total).length){box.innerHTML='<p style="position:relative;z-index:1;color:var(--muted)">Marque um upgrade para calcular.</p>';return}box.innerHTML='<table class=missing-table><thead><tr><th>Material</th><th>Precisa</th><th>Tem</th><th>Falta</th></tr></thead><tbody>'+Object.entries(total).map(([k,v])=>{let have=inv[k]||0,miss=Math.max(0,v-have);return`<tr><td><b>${k}</b></td><td>${v}</td><td>${have}</td><td><b style='color:${miss?'var(--wine)':'var(--moss)'}'>${miss||'OK'}</b></td></tr>`}).join('')+'</tbody></table>'}
function persist(){const saved=JSON.parse(localStorage.getItem('trg-todos')||'{}');$$('.task[data-persist]').forEach(t=>{const i=$('input',t),k=t.dataset.persist;i.checked=!!saved[k];i.onchange=()=>{saved[k]=i.checked;localStorage.setItem('trg-todos',JSON.stringify(saved))}})}
function nav(){const links=$$('.app-nav a'),secs=$$('.page');function act(){let cur='home',y=scrollY+innerHeight*.25;secs.forEach(s=>{if(s.offsetTop<=y)cur=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href').slice(1)===cur))}addEventListener('scroll',act,{passive:true});act()}
function modal(){const st=document.createElement('style');st.textContent=`.more-info{margin-top:10px;border:1px solid #ad7741;border-radius:999px;background:#e7bf80;color:#4b2a16;padding:8px 10px;font-weight:950;width:100%}.detail-backdrop{position:fixed;inset:0;background:rgba(15,8,3,.62);display:none;align-items:flex-end;z-index:90}.detail-backdrop.open{display:flex}.detail-sheet{width:min(100%,760px);margin:0 auto;background:linear-gradient(180deg,var(--paper),var(--paper-2));border:2px solid #8e5a31;border-radius:24px 24px 0 0;box-shadow:0 -20px 60px rgba(0,0,0,.45);padding:18px 16px calc(22px + var(--safe-bottom));max-height:80svh;overflow:auto;color:var(--ink)}.detail-sheet h2{margin:.2rem 0 .3rem;font-family:Georgia,serif}.detail-sheet p{color:var(--muted);line-height:1.45}.detail-grid{display:grid;gap:8px;margin-top:10px}.detail-row{background:rgba(255,245,222,.7);border:1px solid #b77a40;border-radius:14px;padding:10px}.detail-close{float:right;border:1px solid #ad7741;border-radius:999px;background:#e7bf80;color:#4b2a16;padding:8px 12px;font-weight:950}`;document.head.appendChild(st);document.body.insertAdjacentHTML('beforeend',`<div id="detailBackdrop" class="detail-backdrop"><div class="detail-sheet"><button id="detailClose" class="detail-close" type="button">Fechar</button><div id="detailContent"></div></div></div>`);$('#detailClose').onclick=()=>$('#detailBackdrop').classList.remove('open');$('#detailBackdrop').addEventListener('click',e=>{if(e.target.id==='detailBackdrop')e.currentTarget.classList.remove('open')})}
function openDetail(el){let raw={};try{raw=JSON.parse(decodeURIComponent(el.dataset.raw||'%7B%7D'))}catch(e){}const title=raw.name||el.dataset.title||'Detalhes',kind=raw.kind||el.dataset.kind||'Info',desc=raw.desc||raw.notes||el.dataset.desc||'';const rows=Object.entries(raw).filter(([k,v])=>!['search','desc'].includes(k)&&v!=null&&String(v).trim()!=='').map(([k,v])=>`<div class='detail-row'><b>${esc(k)}</b><br><span>${esc(Array.isArray(v)?v.join(', '):v)}</span></div>`).join('');$('#detailContent').innerHTML=`<span class='tag'>${esc(kind)}</span><h2>${esc(title)}</h2><p>${esc(desc)}</p><div class='detail-grid'>${rows}</div>`;$('#detailBackdrop').classList.add('open')}
renderHome();renderGuia();renderDatabase();renderRilia();renderPlanner();renderFontes();modal();persist();nav();$('#searchInput').oninput=filter;$('#categorySelect').onchange=()=>{location.hash='#database';filter()};$('#searchForm').onsubmit=e=>{e.preventDefault();location.hash='#database';filter()};document.addEventListener('click',e=>{if(e.target.matches('.chip')){e.preventDefault();$('#categorySelect').value=e.target.dataset.filter;$$('.chip').forEach(c=>c.classList.toggle('active',c===e.target));filter()}const src=e.target.closest('.detail-source');if(src&&!e.target.closest('.fav'))openDetail(src)});document.addEventListener('input',e=>{if(e.target.matches('[data-inv]'))calc()});document.addEventListener('change',e=>{if(e.target.matches('[data-recipe]'))calc()});$('#themeBtn').onclick=()=>document.body.classList.toggle('bright');filter();
})();
