window.TR_DATA={
  generated:'2026-06-16',
  tools:[
    {name:'Bucket / Balde',tier:'Basic',recipe:'Tutorial/basic tool',use:'Draw water from the well; refill animal troughs, irrigation and recipes.'},
    {name:'Mop / Esfregão',tier:'Basic',recipe:'Tutorial/basic tool',use:'Clean messes. Also used by the game for some odd interactions.'},
    {name:'Copper Pickax / Picareta de Cobre',tier:'Copper',recipe:'25 Copper Bar + 35 Wooden Planks',use:'Mine metal ores and stones.'},
    {name:'Iron Pickax / Picareta de Ferro',tier:'Iron',recipe:'Copper Pickax + 30 Iron Bar + 60 Wooden Planks',use:'Recommended first upgrade for Ore Galore progression.'},
    {name:'Cobalt Pickax / Picareta de Cobalto',tier:'Cobalt',recipe:'Iron Pickax + 45 Cobalt Bar + 40 Noble Wooden Planks',use:'Advanced mining and cobalt progression.'},
    {name:'Copper Axe / Machado de Cobre',tier:'Copper',recipe:'25 Copper Bar + 35 Wooden Planks',use:'Cut trees and clear terrain.'},
    {name:'Iron Axe / Machado de Ferro',tier:'Iron',recipe:'Copper Axe + 30 Iron Bar + 60 Wooden Planks',use:'Second recommended upgrade for terrain cleanup.'},
    {name:'Cobalt Axe / Machado de Cobalto',tier:'Cobalt',recipe:'Iron Axe + 45 Cobalt Bar + 40 Noble Wooden Planks',use:'Advanced tree and obstacle clearing.'},
    {name:'Copper Shovel / Pá de Cobre',tier:'Copper',recipe:'15 Copper Bar + 25 Wooden Planks',use:'Remove grass, remove crops and dig treasure spots.'},
    {name:'Iron Shovel / Pá de Ferro',tier:'Iron',recipe:'Copper Shovel + 25 Iron Bar + 40 Wooden Planks',use:'Shovel upgrade.'},
    {name:'Cobalt Shovel / Pá de Cobalto',tier:'Cobalt',recipe:'Iron Shovel + 30 Cobalt Bar + 30 Noble Wooden Planks',use:'Advanced terrain cleanup.'},
    {name:'Copper Hoe / Enxada de Cobre',tier:'Copper',recipe:'10 Copper Bar + 20 Wooden Planks',use:'Till and refill soil.'},
    {name:'Iron Hoe / Enxada de Ferro',tier:'Iron',recipe:'Copper Hoe + 10 Iron Bar + 30 Wooden Planks',use:'Hoe upgrade.'},
    {name:'Cobalt Hoe / Enxada de Cobalto',tier:'Cobalt',recipe:'Iron Hoe + 15 Cobalt Bar + 20 Noble Wooden Planks',use:'Advanced farming.'},
    {name:'Copper Watering Can / Regador de Cobre',tier:'Copper',recipe:'20 Copper Bar + 30 Wooden Planks',use:'Water crops.'},
    {name:'Iron Watering Can / Regador de Ferro',tier:'Iron',recipe:'Copper Watering Can + 30 Iron Bar + 50 Wooden Planks',use:'Watering upgrade.'},
    {name:'Cobalt Watering Can / Regador de Cobalto',tier:'Cobalt',recipe:'Iron Watering Can + 40 Cobalt Bar + 30 Noble Wooden Planks',use:'Advanced watering.'}
  ],
  vendors:[
    {name:'Buzz',shop:'Farm Buildings / Construções da fazenda',hours:'Construction starts next morning after purchase',sells:'Builds Chicken Coop / Galinheiro and Barn / Celeiro, plus upgrades.'},
    {name:'Holly',shop:'Animal Shop / Animais',hours:'After animal building is complete',sells:'Chicken, Cow, Sheep and Pig.'},
    {name:'Woody',shop:'Carpenter / Sawmill',hours:'09:00-22:00, Monday-Saturday',sells:'Blueprints, recipes and ready-made items for editing the tavern.'},
    {name:'Amos',shop:'City Tavern',hours:'08:00-23:00, Monday-Saturday',sells:'Tavern and brewing supplies.'},
    {name:'Hallmund',shop:'Tool Shop / Blacksmith',hours:'08:40-22:00, Monday-Saturday',sells:'Copper tools and upgrades to Iron/Cobalt tools.'},
    {name:'Petra',shop:'Blacksmith',hours:'09:00-22:00, Monday-Saturday',sells:'Forge and blacksmith-related shop.'},
    {name:'Kujaku',shop:'Fishmonger / Peixaria',hours:'08:15-22:00, Monday-Saturday',sells:'Fish, including Oily Fish options depending on stock.'},
    {name:'Rhia',shop:'Produce Shop',hours:'08:10-22:00, Monday-Saturday',sells:'Crops and produce.'},
    {name:'Lia',shop:'Seed Shop / Sementes',hours:'08:10-22:00, Monday-Saturday',sells:'Seeds and sprouts.'},
    {name:'Chuck',shop:'Butcher / Açougue',hours:'08:20-22:00, Monday-Saturday',sells:'Meat products and ingredients.'},
    {name:'Agatha',shop:'Decor Shop',hours:'08:15-22:00, Monday-Saturday',sells:'Furniture, lighting and decor.'},
    {name:'Markus',shop:'The Burrow',hours:'09:00-22:00, Monday-Saturday',sells:'Pet items, treats and rescue services.'},
    {name:'Nessy',shop:'The Burrow',hours:'09:00-22:00, Monday-Saturday',sells:'Pet items, Jacky quest and adoption path.'}
  ],
  locations:[
    {name:'Rilia',type:'Town shopping district',notes:'Main town with vendors, recipes and services.'},
    {name:'Tavern Grounds / Farm / Terreno',type:'Home area',notes:'Main land for clearing, farming, trees, obstacles and tavern expansion.'},
    {name:'The Mine / Mina',type:'Ore Galore unlockable area',notes:'Unlock after freeing Ferro. Daily regenerating mine floors with ores and chests.'},
    {name:'Mountain / Hot Springs',type:'North area',notes:'Use hot water route to free Ferro and access the mine.'},
    {name:'The Burrow',type:'Animal rescue shelter',notes:'Markus and Nessy; Jacky quest; cat adoption path.'},
    {name:'Beach / Praia',type:'Saltwater fishing',notes:'Saltwater fish and beach forageables.'},
    {name:'River Bank / Rio',type:'Freshwater fishing',notes:'Freshwater fish location, useful for Oily Fish candidates.'},
    {name:'Campsite',type:'South location',notes:'Listed as a southern Rilia location.'},
    {name:'Altar',type:'North location',notes:'Listed in Rilia navigation.'}
  ],
  materials:[
    {name:'Chicken Coop / Galinheiro',group:'Construção / Farm Building / Animal Building',get:'Built by Buzz. Requires items in inventory when placing order.',notes:'Aliases: galinheiro, coop, chicken coop, galinha, galinhas. Build cost: 25 Wooden Planks + 15 Iron Nails + 10 Mortar + 15 Gold. Construction takes a few days. Max 2 coops. Level 1 capacity: 4 chickens. Level 2 capacity: 5 chickens. Level 3 capacity: 6 chickens.',materials:'25 Wooden Planks; 15 Iron Nails; 10 Mortar; 15 Gold',capacity:'Level 1: 4 chickens; Level 2: 5 chickens; Level 3: 6 chickens',upgrades:'Level 2: 30 Wooden Planks + 20 Iron Nails + 12 Mortar + 35 Gold. Level 3: 50 Wooden Planks + 30 Iron Nails + 15 Mortar + 50 Gold.',source:'Fandom Chicken Coop'},
    {name:'Barn / Celeiro',group:'Construção / Farm Building / Animal Building',get:'Built by Buzz. Houses cows, sheep and pigs.',notes:'Aliases: celeiro, barn, vaca, porco, ovelha. Only 1 Barn can be built per farm. Initial construction takes 3 days. Fully upgraded total cost listed as 135 Gold + 190 Wooden Planks + 135 Iron Nails + 60 Mortar. Starting Barn has 4 stalls and can be upgraded up to 8 stalls.',materials:'Fully upgraded total: 135 Gold; 190 Wooden Planks; 135 Iron Nails; 60 Mortar',capacity:'Starts with 4 stalls; upgrades up to 8 stalls',source:'Fandom Barn'},
    {name:'Chicken / Galinha',group:'Animal',get:'Buy from Holly after Chicken Coop is built.',notes:'Aliases: galinha, hen, chicken. Produces Egg every 2 days at maximum growth rate. Place it in coop using Decoration Mode.'},
    {name:'Egg / Ovo',group:'Animal Product / Ingrediente',get:'Chicken Coop collects eggs automatically.',notes:'Aliases: ovo, ovos. Chickens produce 1 Egg every 2 days at maximum growth rate.'},
    {name:'Seeds Mix / Mistura de Sementes',group:'Animal Food',get:'Forage Table / crafting animal food.',notes:'Chicken food. Galinhas comem Seeds Mix.'},
    {name:'Hay / Feno',group:'Animal Food',get:'Forage Table / animal feed crafting.',notes:'Cows and sheep eat Hay.'},
    {name:'Leftovers / Restos',group:'Animal Food',get:'Forage Table / animal feed crafting.',notes:'Pigs eat Leftovers.'},
    {name:'Bucket with Water / Balde com Água',group:'Animal Care',get:'Fill bucket at well.',notes:'Use to refill coop/barn troughs.'},
    {name:'Iron Ore',group:'Ore',get:'Mine and ore nodes',notes:'Smelt into Iron Bars.'},
    {name:'Iron Bar',group:'Metal',get:'Smelter',notes:'Core material for iron upgrades.'},
    {name:'Cobalt Ore',group:'Ore',get:'Mine later floors',notes:'Smelt into Cobalt Bars.'},
    {name:'Cobalt Bar',group:'Metal',get:'Processed from Cobalt Ore',notes:'Needed for cobalt tools.'},
    {name:'Wooden Planks',group:'Wood',get:'Sawmill/wood processing',notes:'Needed for tool upgrades, Chicken Coop, Barn and construction.'},
    {name:'Noble Wooden Planks',group:'Wood',get:'Processed from Noble Wood',notes:'Needed for cobalt upgrades.'},
    {name:'Iron Nails',group:'Metal / Construction',get:'Crafting/blacksmithing resource',notes:'Needed for Chicken Coop and Barn construction/upgrades.'},
    {name:'Mortar',group:'Stone / Construction',get:'Stone crafting/construction resource',notes:'Needed for Chicken Coop and Barn construction/upgrades.'},
    {name:'Queen Bee / Abelha Rainha',group:'Beekeeping',get:'Rare drop from mature trees outside tavern',notes:'Aliases: abelha rainha, queen bee. Used for Apiary.'},
    {name:'Apiary / Apiário',group:'Beekeeping / Crafter',get:'Beekeeping construction/crafter',notes:'Aliases: apiario, colmeia. Produces Honey and Beeswax once you have bees.'},
    {name:'Honey / Mel',group:'Beekeeping',get:'Apiary or limited vendors',notes:'Cooking and brewing ingredient.'},
    {name:'Beeswax / Cera de Abelha',group:'Beekeeping',get:'Apiary',notes:'Crafting ingredient.'}
  ],
  fish:[
    {name:'Oily Fish / Peixe Oleoso',type:'Ingredient group',get:'Fishing or Kujaku',notes:'Aliases: peixe oleoso. Includes Trout, Piranha, Salmon, Eel, Anchovy, Gilt-Head Bream, Sea Bass and Sardine.'},
    {name:'Anchovy / Anchova',type:'Oily Fish',get:'Beach / saltwater',notes:'Good early target if season matches.'},
    {name:'Eel / Enguia',type:'Oily Fish',get:'Beach / saltwater',notes:'Check season and bait.'},
    {name:'Salmon / Salmão',type:'Oily Fish',get:'Freshwater fishing',notes:'Useful for Oily Fish recipes.'},
    {name:'Trout / Truta',type:'Oily Fish',get:'Freshwater fishing',notes:'Useful early Oily Fish candidate.'},
    {name:'Sardine / Sardinha',type:'Oily Fish',get:'Saltwater / beach',notes:'Oily Fish candidate.'}
  ],
  seeds:[
    {name:'Aroma Hops Seeds',category:'Hops'}, {name:'Bitter Hops Seeds',category:'Hops'}, {name:'Citra Hops Seeds',category:'Hops'}, {name:'Galaxy Hops Seeds',category:'Hops'},
    {name:'Barley Grains',category:'Grain'}, {name:'Wheat Grains',category:'Grain'}, {name:'Rye Grains',category:'Grain'}, {name:'Rice Grains',category:'Grain'},
    {name:'Beetroot Seeds',category:'Vegetable'}, {name:'Carrot Seeds',category:'Vegetable'}, {name:'Corn Kernels',category:'Vegetable'}, {name:'Tomato Seeds',category:'Vegetable'}, {name:'Pumpkin Seeds',category:'Vegetable'},
    {name:'Apple Sprout',category:'Fruit tree'}, {name:'Lemon Sprout',category:'Fruit tree'}, {name:'Orange Sprout',category:'Fruit tree'}, {name:'Pear Sprout',category:'Fruit tree'}, {name:'Plum Sprout',category:'Fruit tree'},
    {name:'Black Tea Seeds',category:'Tea'}, {name:'Green Tea Seeds',category:'Tea'}, {name:'Red Tea Seeds',category:'Tea'}, {name:'White Tea Seeds',category:'Tea'}
  ],
  food:[
    {name:'Anchovies in Oil / Anchovas no Óleo',category:'Recipe • Ingredients include Oily Fish / Anchovy + Oil. Use search: peixe oleoso, receita.'},
    {name:'Fried Fish / Peixe Frito',category:'Recipe • Fish dish. Search aliases: peixe, peixe frito, recipe, receita.'},
    {name:'Roasted Fish / Peixe Assado',category:'Recipe • Fish dish. Search aliases: peixe assado, roasted fish.'},
    {name:'Fish Soup / Sopa de Peixe',category:'Recipe • Fish dish. Search aliases: sopa de peixe.'},
    {name:'Fish Stew / Ensopado de Peixe',category:'Recipe • Fish dish. Search aliases: ensopado peixe.'},
    {name:'Fish Curry',category:'Recipe • Fish dish. Search aliases: curry peixe.'},
    {name:'Grilled Steak / Bife Grelhado',category:'Recipe • Meat dish.'},
    {name:'Sausage / Linguiça',category:'Recipe • Meat product.'},
    {name:'Pumpkin Pie / Torta de Abóbora',category:'Recipe • Dessert/vegetable dish.'},
    {name:'Bread / Pão',category:'Recipe • Basic food.'},
    {name:'Brownie',category:'Recipe • Dessert.'},
    {name:'Carrot Cake / Bolo de Cenoura',category:'Recipe • Dessert.'},
    {name:'Honey Flan / Pudim de Mel',category:'Recipe • Honey dessert. Search: mel, honey.'},
    {name:'Yogurt with Honey / Iogurte com Mel',category:'Recipe • Honey dairy recipe. Search: mel, honey.'},
    {name:'Spaghetti Bolognese',category:'Recipe • Meat/grain dish.'},
    {name:'Ramen',category:'Recipe • Noodle dish.'},
    {name:'Salad / Salada',category:'Recipe • Vegetable dish.'},
    {name:'Tomato Soup / Sopa de Tomate',category:'Recipe • Vegetable soup.'}
  ],
  brewing:[
    {name:'Fruit Juice / Suco de Fruta',station:'Press',ingredients:'Fruit (2)',notes:'Can be served immediately; cannot be aged.'},
    {name:'Lager',station:'Fermentation Tank',ingredients:'Malt from Barley/Wheat + Bitter/Aroma Hops + Lager Yeast + Bucket with Water',notes:'Early beer.'},
    {name:'Amber Ale',station:'Fermentation Tank',ingredients:'Malt from Rye/Corn + Citra/Dual Hops + Ale Yeast + Bucket with Water',notes:'Early ale.'},
    {name:'Strong Ale',station:'Fermentation Tank',ingredients:'Toasted malt + hops + ale yeast + water',notes:'Sweet and full-bodied.'},
    {name:'Chocolate Lager',station:'Fermentation Tank',ingredients:'Toasted malt + hops + lager yeast + chocolate + water',notes:'Dessert-ish beer.'},
    {name:'Vanilla Ale',station:'Fermentation Tank',ingredients:'Toasted malt + hops + ale yeast + vanilla + water',notes:'Sweet ale.'},
    {name:'Wine / Vinho',station:'Brewing Barrel',ingredients:'Fruit juice + wine yeast',notes:'Barrel drink.'},
    {name:'Cider / Sidra',station:'Brewing Barrel',ingredients:'Fruit base + yeast',notes:'Barrel drink.'},
    {name:'Mead / Hidromel',station:'Brewing Barrel',ingredients:'Honey base + yeast/water',notes:'Useful with Apiary honey.'}
  ],
  quests:[
    {name:'Unlock the Mine / Ferro / Liberar a Mina',notes:'Reach hot springs, use hot water to free Ferro, then mine unlocks.'},
    {name:'Jacky the Cat / Gato Jacky',notes:'Talk to Nessy at The Burrow; find Jacky under a cart, in a barrel, then in a tree behind a bench.'},
    {name:'Build Chicken Coop / Construir Galinheiro',notes:'Ask Buzz to build it. Keep 25 Wooden Planks, 15 Iron Nails, 10 Mortar and 15 Gold in inventory.'},
    {name:'Buy Chicken / Comprar Galinha',notes:'After the Chicken Coop is complete, Holly sells chickens.'},
    {name:'Chicken Care / Cuidar da Galinha',notes:'Place chicken in coop using Decoration Mode. Feed with Seeds Mix and fill trough with Bucket with Water.'}
  ],
  sources:[
    {label:'Travellers Rest Fandom Chicken Coop',url:'https://travellers-rest.fandom.com/wiki/Chicken_Coop',why:'Chicken Coop construction costs, capacities and upgrades.'},
    {label:'Travellers Rest Fandom Animals',url:'https://travellers-rest.fandom.com/wiki/Animals',why:'Animal care, produce and assigning animals.'},
    {label:'Travellers Rest Fandom Barn',url:'https://travellers-rest.fandom.com/wiki/Barn',why:'Barn construction, features and total upgraded cost.'},
    {label:'Travellers Rest Wiki/Fandom tools',url:'https://travellers-rest.fandom.com/wiki/Tools',why:'Tool and upgrade costs.'},
    {label:'Rilia vendors',url:'https://travellers-rest.fandom.com/wiki/Rilia',why:'Vendor list and hours.'},
    {label:'Brewing',url:'https://travellers-rest.fandom.com/wiki/Brewing',why:'Brewing stations and recipe structure.'},
    {label:'Food category',url:'https://travellers-rest.fandom.com/wiki/Category:Food',why:'Food index.'},
    {label:'Seeds category',url:'https://travellers-rest.fandom.com/wiki/Category:Seeds',why:'Seed and sprout names.'}
  ]
};
